name: Nightly Pipeline

on:
  workflow_dispatch:
    inputs:
      dryrun:
        type: boolean
        default: false
  schedule:
    - cron: '0 3 * * *'

jobs:
  PackageUpdate:
    # This is intentionally disabled to prevent npm updates, otherwise it is
    # causing an endless dependency update loop for fiftyone.* packages in this
    # repository.
    # TODO: Don't forget to add this job to PullRequests' needs when enabling back.
    if: false
    name: Nightly Package Update
    uses: 51Degrees/common-ci/.github/workflows/nightly-package-update.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}

  PullRequests:
    if: ${{ !cancelled() }}
    # needs: PackageUpdate
    name: Nightly Pull Requests
    uses: 51Degrees/common-ci/.github/workflows/nightly-pull-requests.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      TestResourceKey: ${{ secrets.SUPER_RESOURCE_KEY}}
      DeviceDetection: ${{ secrets.DEVICE_DETECTION_KEY }}

  Publish:
    if: ${{ !cancelled() }}
    needs: PullRequests
    name: Nightly Publish
    uses: 51Degrees/common-ci/.github/workflows/nightly-publish.yml@main
    with:
      repo-name: ${{ github.event.repository.name }}
      org-name: ${{ github.event.repository.owner.login }}
      dryrun: ${{ inputs.dryrun || false }}
    secrets:
      token: ${{ secrets.ACCESS_TOKEN }}
      TestResourceKey: ${{ secrets.SUPER_RESOURCE_KEY}}
      DeviceDetection: ${{ secrets.DEVICE_DETECTION_KEY }}
      NPMAuthToken: ${{ secrets.NPM_AUTH_TOKEN}}

